BaSP-TG: Tasks methods connected to BBDD.
BaSP-a2022/capi-b-trackgenix-server pull request #14
Opened 2022-10-17 09:16 UTC by mr-valen

2022-10-18 03:31 UTC, Juanoauil commented on src/controllers/tasks.js
> +      data: tasks,
if we send a request with an incorrect id, we will receive as a response that employee found

2022-10-18 03:33 UTC, Juanoauil commented
please delete data folder

2022-10-18 03:36 UTC, Juanoauil commented on src/controllers/tasks.js
> +    return res.status(204).json();
we can delete an inexistent id, that is correct?

2022-10-18 03:59 UTC, Juanoauil requested changes
please fix comments

2022-10-18 06:13 UTC, mr-valen commented on src/controllers/tasks.js
> +      data: tasks,
I think that case was when the the incorrent ID exists in the data base but was deleted, now it's fixed.

2022-10-18 06:13 UTC, mr-valen commented on src/controllers/tasks.js
> +    return res.status(204).json();
Fixed.

2022-10-19 15:07 UTC, Juanoauil commented
you have 2 postman collection

2022-10-21 20:32 UTC, Baldizan commented
Models files name format must be capitalized.

2022-10-21 20:45 UTC, Baldizan commented on src/controllers/tasks.js
> +import TaskModel from '../models/tasks';
It is suggested to remove other entities' Controllers files **content**, since it contains errors, and future conflicts will be easier to resolve.

2022-10-22 17:33 UTC, Juanoauil approved these changes

2022-10-22 17:34 UTC, merged