BaSP-TG: employee - getByRate and change
BaSP-a2022/capi-b-trackgenix-server pull request #7
Opened 2022-10-11 22:33 UTC by FabianDutraSilva

2022-10-12 01:22 UTC, Juanoauil requested changes

2022-10-12 01:22 UTC, Juanoauil commented on src/resources/employees.js
> +      if (project.rate === rateNumber) {
if there is no employee, it does not return an error

2022-10-12 01:31 UTC, Juanoauil commented on src/resources/employees.js
> +        res.send('Employee does not exist');
replace the message for 'Employee not found'

2022-10-12 02:14 UTC, FabianDutraSilva commented on src/resources/employees.js
> +        res.send('Employee does not exist');
already committed and pushed the fixed js

2022-10-12 02:15 UTC, Juanoauil submitted a review, later dismissed

2022-10-13 19:38 UTC, Juanoauil approved these changes

2022-10-13 19:38 UTC, merged